services:
  grafana:
    image: docbuc/grafana
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=geheim
  telegraf:
    image: docbuc/telegraf
    build: telegraf/
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - INFLUXDB_TOKEN=gahPae6deivo0aenooy7thoheewaex9eeNgaePah8dee5io6neewooSe3bemu9gi
      - INFLUXDB_ORG=dockerbuch
      - INFLUXDB_BUCKET=dockerbuch
  influx:
    image: influxdb:2.7
    restart: unless-stopped
    # ports:
    #   - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=dockerbuch
      - DOCKER_INFLUXDB_INIT_PASSWORD=geheimgeheim
      - DOCKER_INFLUXDB_INIT_ORG=dockerbuch
      - DOCKER_INFLUXDB_INIT_BUCKET=dockerbuch
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=gahPae6deivo0aenooy7thoheewaex9eeNgaePah8dee5io6neewooSe3bemu9gi
